# Site
repository: gazis/gazis.github.io
favicon: images/favicon.ico

#
# Personal information
#
name: Evangelos (Vangelis) Gazis
title: BSc, MSc, MBA, PhD
email: gazisvangelis@gmail.com
website: https://gazis.github.io

#
# Dark Mode (true/false/never)
#
darkmode: false

#
# Social
#
twitter_username: gazisvangelis
github_username:  gazis
# stackoverflow_username: N/A
# dribbble_username: gazis
# facebook_username: gazisvangelis
# flickr_username: gazisvangelis
instagram_username: gazisvangelis
linkedin_username: vangelisgazis
# xing_username: N/A
youtube_username: gazisvangelis
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
    My name is Vangelis and I am, for the most part, a computer science person (I am not really fond of the term "IT"). I grew scientifically through research in wireless mobile systems (<mark>3G</mark>, <mark>4G</mark>, <mark>5G</mark>). I particularly focus on <mark>systems design</mark> for adaptable distributed systems (e.g. cognitive networks, autonomic networks, etc.). These concerns include <mark>design principles</mark> and <mark>design patterns</mark> through which one can develop systems capable of <mark>adaptation</mark> and <mark>agility</mark>.

    That research lead to extensive work on <mark>software engineering</mark> in support of <mark>adaptable systems</mark> that can dynamically alter their own behaviour. Key <mark>control aspects</mark> of such adaptable systems include algorithms that, given a corpus of capabilities, enable the <mark>dynamic discovery</mark> of features that meet application requirements. The <mark>dynamic assembly</mark> of a <mark>system's personality</mark> (i.e. set of behaviours) finds applications in a wide range of domains where requirements may change over time. The capacity to dynamically assemble a particular <mark>personality</mark> is a pillar of <mark>technological agility</mark> and an enabler of innovation.

    For instance, in the domain of modern network architectures reliant on virtualization, such as 5G, given the capabilities of the protocols found in the 5G standards, these algorithms enable the discovery of software layers, including the protocol stack ones, that meet the requirements of the logical interfaces among 5G elements. Another enabler is the on-demand adaptation of a system's code during runtime to match a given set of features (e.g. when a protocol must undergo an update during runtime to accommodate a change in requirements or to incorporate a security patch for a vulnerability).

    Since 2010 I have been active on the <mark>Internet of Things</mark> domain, where I led projects in the areas of <mark>Smart Home</mark> and <mark>Smart Grid</mark>, <mark>Industrial Cyber Physical Systems</mark>, <mark>Big Data</mark>, and <mark>Data Analytics</mark>.

    Recently I have been focusing more intently on <mark>cybersecurity</mark>, where I contribute in a senior leadership capacity to the assessment of R&D programmes, the development of European <mark>best practice recommendations</mark>, and the advancement of <mark>technical standards</mark>. I am particularly interested in <mark>systemic approaches</mark> to <mark>resilience</mark> through the interplay of technological, policy and economic considerations. I advance these agendas as a member of these organizations:
    -   European Network and Information Security Agency <mark>(ENISA)</mark> Expert Group (EG) on IoT Security <mark>(IoTSec)</mark>
    -   European Commission (EC) Directorate General (DG) Mobility <mark>(MOVE)</mark> Expert Group (EG) on <mark>C-ITS PKI</mark>
    -   European Telecommunications Standards Institute <mark>(ETSI)</mark> Technical Committee (TC) on Cybersecurity <mark>(CYBER)</mark>
    -   GSM Association <mark>(GSMA)</mark>
        -   Fraud and Security Architecture Group <mark>(FSAG)</mark>
        -   Device Security Group <mark>(DSG)</mark>
        -   IoT SAFE Group <mark>(IOTSAFE)</mark>
    -   European Cyber Security Organization <mark>(ECSO)</mark>
        -   WG1 <mark>Cybersecurity Certification</mark>
        -   WG6 <mark>Strategic Research Agenda</mark>

# Experience Section
# experience_title: Experience

# Expertise Section
# expertise_title: Expertise

# Education Section
# education_title: Education

# Projects Section
# projects_title: Research Projects

# More Section
# more_title: A Little More About Me
more_content: | # Include new lines to allow paragraphs
    Other interests that I have include:
    -   Hiking
    -   Swimming
    -   Photography (check out my Instagram feed for photos)

# Footer
footer_show_references: true

#
# Build settings
#

#
# https://github.com/benbalter/jekyll-remote-theme
#
remote_theme: sproogen/resume-theme

sass:
    sass_dir: _sass
    style: compressed

plugins:
-   jekyll-seo-tag

#
# Update
#
exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
